/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'
import { Route as AuthenticatedSafeRouteRouteImport } from './routes/_authenticated/safe-route'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCircleRouteImport } from './routes/_authenticated/circle'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiPublicHooksIngestIncidentsRouteImport } from './routes/api/public/hooks/ingest-incidents'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafeRouteRoute = AuthenticatedSafeRouteRouteImport.update({
  id: '/safe-route',
  path: '/safe-route',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCircleRoute = AuthenticatedCircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksIngestIncidentsRoute =
  ApiPublicHooksIngestIncidentsRouteImport.update({
    id: '/api/public/hooks/ingest-incidents',
    path: '/api/public/hooks/ingest-incidents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/circle': typeof AuthenticatedCircleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/safe-route': typeof AuthenticatedSafeRouteRoute
  '/sos': typeof AuthenticatedSosRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/ingest-incidents': typeof ApiPublicHooksIngestIncidentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/circle': typeof AuthenticatedCircleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/safe-route': typeof AuthenticatedSafeRouteRoute
  '/sos': typeof AuthenticatedSosRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/ingest-incidents': typeof ApiPublicHooksIngestIncidentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/circle': typeof AuthenticatedCircleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/safe-route': typeof AuthenticatedSafeRouteRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/ingest-incidents': typeof ApiPublicHooksIngestIncidentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/assistant'
    | '/circle'
    | '/dashboard'
    | '/history'
    | '/map'
    | '/profile'
    | '/report'
    | '/safe-route'
    | '/sos'
    | '/statistics'
    | '/api/chat'
    | '/api/public/hooks/ingest-incidents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/assistant'
    | '/circle'
    | '/dashboard'
    | '/history'
    | '/map'
    | '/profile'
    | '/report'
    | '/safe-route'
    | '/sos'
    | '/statistics'
    | '/api/chat'
    | '/api/public/hooks/ingest-incidents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alerts'
    | '/_authenticated/assistant'
    | '/_authenticated/circle'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/_authenticated/safe-route'
    | '/_authenticated/sos'
    | '/_authenticated/statistics'
    | '/api/chat'
    | '/api/public/hooks/ingest-incidents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksIngestIncidentsRoute: typeof ApiPublicHooksIngestIncidentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safe-route': {
      id: '/_authenticated/safe-route'
      path: '/safe-route'
      fullPath: '/safe-route'
      preLoaderRoute: typeof AuthenticatedSafeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circle': {
      id: '/_authenticated/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof AuthenticatedCircleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/ingest-incidents': {
      id: '/api/public/hooks/ingest-incidents'
      path: '/api/public/hooks/ingest-incidents'
      fullPath: '/api/public/hooks/ingest-incidents'
      preLoaderRoute: typeof ApiPublicHooksIngestIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCircleRoute: typeof AuthenticatedCircleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSafeRouteRoute: typeof AuthenticatedSafeRouteRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCircleRoute: AuthenticatedCircleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSafeRouteRoute: AuthenticatedSafeRouteRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksIngestIncidentsRoute: ApiPublicHooksIngestIncidentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
